version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users:/Users:ro  # Mount host filesystem for Docker Compose operations
      - /tmp:/tmp  # Mount host /tmp to container /tmp for dump/restore file sharing
    env_file:
      - .env.example
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_ENV=development
    depends_on:
      - backend
    restart: unless-stopped
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dump_restore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dump_restore"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes:
  pgdata:
  frontend_node_modules:
